language: go
go:
  - 1.13.x

cache:
  directories:
    - $GOPATH/pkg/mod
dist: trusty
sudo: false
install: true

before_install:
  - sudo apt-get install -y hugo
  - curl -sSf http://uptoc.saltbo.cn/install.sh | sh
addons:
  apt:
  update: true
  
script:
  - make

deploy:
  - provider: script
  - script: uptoc --endpoint oss-cn-zhangjiakou.aliyuncs.com --bucket saltbo-blog public
