name: build
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@master
      - name: Check out code
        uses: actions/checkout@v1
      - name: Build
        run: yarn && yarn build
      - name: Deploy
        uses: saltbo/uptoc-action@master
        with:
          access_key: ${{ secrets.UPTOC_UPLOADER_KEYID }}
          access_secret: ${{ secrets.UPTOC_UPLOADER_KEYSECRET }}
          endpoint: oss-cn-zhangjiakou.aliyuncs.com
          bucket: saltbo-blog
          dist: public