name: build
on:
  schedule:
  - cron: "5 * * * *"
  push:
    branches:
      - master
  pull_request:
  workflow_run:
    workflows: ["wakatime"]
    branches: [master]
    types: 
      - completed

jobs:
  sync:
    name: Sync from notion
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Clean the old posts
        run: |
          rm -rf ./docs/posts/*
          rm -rf ./.vuepress/public/images/posts/*
      - name: notion-md-gen
        uses: bonaysoft/notion-md-gen@master
        env:
          NOTION_SECRET : ${{ secrets.NOTION_SECRET }}
      - name: Format documents
        uses: creyD/prettier_action@v3.1
        with:
          prettier_options: --write ./docs/**/*.md
          commit_message: 'notion-md-gen: update articles (auto)'

  build:
    name: Build And Deploy
    runs-on: ubuntu-latest
    needs: [sync]
    steps:
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache dependencies
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build
        run: yarn && yarn build
      - name: Snapshot Repos
        uses: saltbo/actions/snapshot-gh-repos@master
        with:
          repos: "saltbo/zpan,bonaysoft/notion-md-gen,saltbo/uptoc"
          outputFile: public/snapshot-repos.json
      - name: Deploy
        uses: saltbo/uptoc@master
        with:
          driver: qiniu
          region: cn-north-1
          bucket: saltbo-blog
          dist: public
        env:
          UPTOC_UPLOADER_AK: ${{ secrets.UPTOC_UPLOADER_KEYID }}
          UPTOC_UPLOADER_SK: ${{ secrets.UPTOC_UPLOADER_KEYSECRET }}