name: build
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Uptoc
        uses: saltbo/uptoc-action@master
      - name: Set up Node
        uses: actions/setup-node@master
      - name: Check out code
        uses: actions/checkout@v1
      - name: Build
        run: yarn && yarn build
      - name: Deploy
        run: uptoc --endpoint oss-cn-zhangjiakou.aliyuncs.com --bucket saltbo-blog public 
        env:
          UPTOC_UPLOADER_KEYID: ${{ secrets.UPTOC_UPLOADER_KEYID }}
          UPTOC_UPLOADER_KEYSECRET: ${{ secrets.UPTOC_UPLOADER_KEYSECRET }}