name: build
on:
  push:
    branches:
      - master
  issues:
    types: 
      - opened
      - edited
      - deleted
  pull_request:
  workflow_run:
    workflows: ["wakatime"]
    branches: [master]
    types: 
      - completed

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@master
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache dependencies
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Check out code
        uses: actions/checkout@v1
      - name: Fetch Issues
        uses: saltbo/issues2md@master
        with: 
          repo: saltbo/blog
          dist: docs/notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Notion2Github
        uses: younho9/notion2github@v1.1.0
        with:
          database-url: 'https://www.notion.so/acc3dfd0339e4cacb5baae8673fddfad'
          docs-directory: docs/notes2
      - name: Format documents
        uses: creyD/prettier_action@v3.1
        with:
          prettier_options: --write ./docs/notes2/*.md
          commit_message: 'docs: Update notion note docs (auto)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: yarn && yarn build
      - name: Deploy
        uses: saltbo/uptoc@master
        with:
          driver: oss
          region: cn-zhangjiakou
          bucket: saltbo-blog
          dist: public
        env:
          UPTOC_UPLOADER_AK: ${{ secrets.UPTOC_UPLOADER_KEYID }}
          UPTOC_UPLOADER_SK: ${{ secrets.UPTOC_UPLOADER_KEYSECRET }}
